steps:
  - name: 'node:14'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        npm install
        npm run build
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/helloworld-nodejs-zxt:$COMMIT_SHA', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/helloworld-nodejs-zxt:$COMMIT_SHA']

substitutions:
  _COMMIT_SHA: $SHORT_SHA